define(function () { 'use strict';

    /*! *****************************************************************************
    Copyright (c) Microsoft Corporation.

    Permission to use, copy, modify, and/or distribute this software for any
    purpose with or without fee is hereby granted.

    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
    REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
    INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
    LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
    OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
    PERFORMANCE OF THIS SOFTWARE.
    ***************************************************************************** */
    var extendStatics=function(t,e){return (extendStatics=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(t,e){t.__proto__=e;}||function(t,e){for(var r in e)e.hasOwnProperty(r)&&(t[r]=e[r]);})(t,e)};function __extends(t,e){function r(){this.constructor=t;}extendStatics(t,e),t.prototype=null===e?Object.create(e):(r.prototype=e.prototype,new r);}var __assign=function(){return (__assign=Object.assign||function(t){for(var e,r=1,n=arguments.length;r<n;r++)for(var o in e=arguments[r])Object.prototype.hasOwnProperty.call(e,o)&&(t[o]=e[o]);return t}).apply(this,arguments)};function __rest(t,e){var r={};for(var n in t)Object.prototype.hasOwnProperty.call(t,n)&&e.indexOf(n)<0&&(r[n]=t[n]);if(null!=t&&"function"==typeof Object.getOwnPropertySymbols){var o=0;for(n=Object.getOwnPropertySymbols(t);o<n.length;o++)e.indexOf(n[o])<0&&Object.prototype.propertyIsEnumerable.call(t,n[o])&&(r[n[o]]=t[n[o]]);}return r}function __awaiter(t,e,r,n){return new(r||(r=Promise))((function(o,a){function i(t){try{u(n.next(t));}catch(t){a(t);}}function c(t){try{u(n.throw(t));}catch(t){a(t);}}function u(t){var e;t.done?o(t.value):(e=t.value,e instanceof r?e:new r((function(t){t(e);}))).then(i,c);}u((n=n.apply(t,e||[])).next());}))}function __generator(t,e){var r,n,o,a,i={label:0,sent:function(){if(1&o[0])throw o[1];return o[1]},trys:[],ops:[]};return a={next:c(0),throw:c(1),return:c(2)},"function"==typeof Symbol&&(a[Symbol.iterator]=function(){return this}),a;function c(a){return function(c){return function(a){if(r)throw new TypeError("Generator is already executing.");for(;i;)try{if(r=1,n&&(o=2&a[0]?n.return:a[0]?n.throw||((o=n.return)&&o.call(n),0):n.next)&&!(o=o.call(n,a[1])).done)return o;switch(n=0,o&&(a=[2&a[0],o.value]),a[0]){case 0:case 1:o=a;break;case 4:return i.label++,{value:a[1],done:!1};case 5:i.label++,n=a[1],a=[0];continue;case 7:a=i.ops.pop(),i.trys.pop();continue;default:if(!(o=i.trys,(o=o.length>0&&o[o.length-1])||6!==a[0]&&2!==a[0])){i=0;continue}if(3===a[0]&&(!o||a[1]>o[0]&&a[1]<o[3])){i.label=a[1];break}if(6===a[0]&&i.label<o[1]){i.label=o[1],o=a;break}if(o&&i.label<o[2]){i.label=o[2],i.ops.push(a);break}o[2]&&i.ops.pop(),i.trys.pop();continue}a=e.call(t,i);}catch(t){a=[6,t],n=0;}finally{r=o=0;}if(5&a[0])throw a[1];return {value:a[0]?a[1]:void 0,done:!0}}([a,c])}}}function __values(t){var e="function"==typeof Symbol&&Symbol.iterator,r=e&&t[e],n=0;if(r)return r.call(t);if(t&&"number"==typeof t.length)return {next:function(){return t&&n>=t.length&&(t=void 0),{value:t&&t[n++],done:!t}}};throw new TypeError(e?"Object is not iterable.":"Symbol.iterator is not defined.")}function __read(t,e){var r="function"==typeof Symbol&&t[Symbol.iterator];if(!r)return t;var n,o,a=r.call(t),i=[];try{for(;(void 0===e||e-- >0)&&!(n=a.next()).done;)i.push(n.value);}catch(t){o={error:t};}finally{try{n&&!n.done&&(r=a.return)&&r.call(a);}finally{if(o)throw o.error}}return i}

    var SearchSubject;!function(s){s.Buildings="buildings",s.Cities="cities",s.Districts="districts",s.PostalCodes="postalcodes",s.PostalCodesCities="postalcodes_cities",s.PostalCodesCitiesDistricts="postalcodes_cities_districts",s.PostalCodesCitiesDistrictsStreets="postalcodes_cities_districts_streets",s.PostalCodesCitiesStreets="postalcodes_cities_streets";}(SearchSubject||(SearchSubject={}));var SearchSubject$1 = SearchSubject;

    var FetchAdapter=function(){function t(){}return t.prototype.request=function(t){var e;return __awaiter(this,void 0,void 0,(function(){var r,n;return __generator(this,(function(o){switch(o.label){case 0:return r=new Request(t.url,{method:t.method,headers:t.headers}),[4,fetch(r)];case 1:return (n=o.sent()).status>=200&&n.status<300?(null===(e=n.headers.get("Content-Type"))||void 0===e?void 0:e.startsWith("application/json"))?[2,n.json()]:[2,n.text()]:400===n.status?[2,n.json().then((function(t){throw new Error("".concat(n.statusText,": ").concat(t.message).trim())}))]:[2,n.text().then((function(t){throw new Error("".concat(n.statusText," ").concat(t).trim())}))]}}))}))},t}();

    var DefaultSettings=function(){function t(){}return t.getAdapter=function(){return new FetchAdapter},t.baseUrl="https://autocomplete2.postdirekt.de/autocomplete2/",t.headers={Accept:"application/json",Authorization:""},t}();

    var SearchRequest=function(e,t,h){void 0===t&&(t="GET"),void 0===h&&(h={}),this.url="",this.method="GET",this.headers={},this.url=e,this.method=t,this.headers=h;};

    var SearchRequestBuilder=function(){function e(e,t){this.addressTypeSupported=[SearchSubject$1.PostalCodesCitiesDistrictsStreets,SearchSubject$1.PostalCodesCitiesStreets],this.baseUrl=e,this.accessToken=t;}return e.prototype.create=function(e){var t=e.subject,r=e.country,s=__rest(e,["subject","country"]);return s.address_type&&this.addressTypeSupported.includes(t)||delete s.address_type,new SearchRequest(this.buildUrl(r,t,s),"GET",__assign(__assign({},DefaultSettings.headers),{Authorization:"Bearer ".concat(this.accessToken)}))},e.prototype.buildUrl=function(t,r,s){var n="".concat(this.baseUrl,"/").concat(t);return n="".concat(n,"/").concat(r),n+=e.buildQueryString(s)},e.buildQueryString=function(e){var t=Object.entries(e).map((function(e){var t=__read(e,2),r=t[0],s=t[1];return "".concat(encodeURIComponent(r),"=").concat(encodeURIComponent(s))})).join("&");return t&&(t="?".concat(t)),t},e}();

    var SearchService=function(){function e(e,r,t){this.adapter=t,this.requestBuilder=new SearchRequestBuilder(r,e);}return e.prototype.search=function(e){return __awaiter(this,void 0,void 0,(function(){return __generator(this,(function(r){switch(r.label){case 0:return [4,this.adapter.request(e)];case 1:return [2,r.sent()]}}))}))},e}();

    var SelectRequestBuilder=function(e){function t(){return null!==e&&e.apply(this,arguments)||this}return __extends(t,e),t.prototype.create=function(t){return e.prototype.create.call(this,t)},t}(SearchRequestBuilder);

    var SelectService=function(){function e(e,t,r){this.adapter=r,this.requestBuilder=new SelectRequestBuilder(t,e);}return e.prototype.select=function(e){return __awaiter(this,void 0,void 0,(function(){return __generator(this,(function(t){return [2,this.adapter.request(e)]}))}))},e}();

    var ServiceFactory=function(){function e(){}return e.createSearchService=function(e){return new SearchService(e,"".concat(DefaultSettings.baseUrl,"search"),DefaultSettings.getAdapter())},e.createSelectService=function(e){return new SelectService(e,"".concat(DefaultSettings.baseUrl,"select"),DefaultSettings.getAdapter())},e.prototype.createSearchService=function(t){return e.createSearchService(t)},e.prototype.createSelectService=function(t){return e.createSelectService(t)},e}();

    var AddressType;!function(e){e.A="A",e.F="F",e.P="P";}(AddressType||(AddressType={}));var AddressType$1 = AddressType;

    var AutocompleteAddressSuggestions=function(){function t(){this.suggestions=[];}return t.prototype.getByUuid=function(t){return this.suggestions.find((function(u){return u.uuid===t}))||null},t}();

    var AutocompleteDomAddress=function(){function e(e){this.inputMap=e;}return Object.defineProperty(e.prototype,"address",{get:function(){var e={city:"",postalCode:"",street:""};return this.inputMap.forEach((function(t,r){e[r]=t.value;})),e},set:function(e){var t,r;try{for(var n=__values(this.inputMap),a=n.next();!a.done;a=n.next()){var o=__read(a.value,2),u=o[0],i=o[1];i.value=e[u],i.dispatchEvent(new Event("change"));}}catch(e){t={error:e};}finally{try{a&&!a.done&&(r=n.return)&&r.call(n);}finally{if(t)throw t.error}}},enumerable:!1,configurable:!0}),e}();

    var Key;!function(r){r.ArrowUp="ArrowUp",r.ArrowDown="ArrowDown",r.Enter="Enter",r.Tab="Tab";}(Key||(Key={}));var Key$1 = Key;

    var ListRenderer=function(){function t(){}return t.prototype.render=function(t,e){var i=this;if(!t.parentElement)throw Error("Input elements without a parent cannot be assigned a suggestion list.");this.remove(),this.currentField=t,t.setAttribute("autocomplete","none");var r=document.createElement("ul");r.setAttribute("id","datalist-".concat(t.id)),r.setAttribute("class","datalist"),r.setAttribute("style","width:".concat(t.offsetWidth,"px; top:").concat(t.offsetHeight,"px;")),e.map((function(t){return {id:t.uuid,title:[t.street,t.postalCode,t.city].filter(Boolean).join(", ")}})).forEach((function(t){var e=document.createElement("li"),i=document.createTextNode(t.title);e.setAttribute("id",t.id),e.setAttribute("data-value",t.title),e.appendChild(i),r.appendChild(e);})),t.parentElement.appendChild(r),t.parentElement.classList.add("autocomplete-container"),r.addEventListener("mousedown",(function(e){var r=e.target;i.itemSelect(r),setTimeout((function(){return t.focus()}),0);})),t.addEventListener("focusout",this.remove.bind(this)),this.removableEventHandler=this.navigationKeyListener.bind(this),t.addEventListener("keydown",this.removableEventHandler);},t.prototype.remove=function(){if(this.removableEventHandler&&this.currentField){var t=document.querySelector('[id="datalist-'.concat(this.currentField.id,'"]'));t&&t.remove(),this.currentField.removeEventListener("keydown",this.removableEventHandler),this.currentField=void 0;}},t.prototype.navigationKeyListener=function(t){t.key in Key$1&&(t.key!==Key$1.Tab&&t.preventDefault(),this.triggerKeydown(t.key));},t.prototype.triggerKeydown=function(t){if(this.currentField){var e=document.querySelector('[id="datalist-'.concat(this.currentField.id,'"]'));if(e){var i=Array.from(e.children),r=e.querySelector("[data-active]"),n=i.find((function(){return !0}));if(r||t!==Key$1.Enter)if(t!==Key$1.ArrowDown||r){if(r){var o=null,a=null;i.forEach((function(t,e,i){t===r&&(o=i[e-1],a=i[e+1]);})),r.removeAttribute("data-active"),t===Key$1.ArrowUp&&(o?((o=o).setAttribute("data-active","true"),o.offsetTop<e.scrollTop&&(e.scrollTop-=o.offsetHeight)):i[i.length-1].setAttribute("data-active","true")),t===Key$1.ArrowDown&&(a?(a=a).setAttribute("data-active","true"):i[0].setAttribute("data-active","true")),t===Key$1.Tab&&this.currentField.focus(),[Key$1.Enter,Key$1.Tab].includes(t)&&this.itemSelect(r);}}else n.setAttribute("data-active","true");}}},t.prototype.itemSelect=function(t){this.currentField&&(this.currentField.dataset.suggestionUuid=t.id,this.currentField.dispatchEvent(new Event("autocomplete:datalist-select")),this.remove());},t}();

    var AddressInputType;!function(e){e.City="city",e.Street="street",e.PostalCode="postalCode";}(AddressInputType||(AddressInputType={}));var AddressInputType$1 = AddressInputType;

    var HintRenderer=function(){function e(e){this.hintText=e;}return e.prototype.render=function(e){if(!e.parentElement)throw Error("Input elements without a parent cannot be assigned a infobox.");if(0!==this.hintText.length){var t=document.createElement("div"),n=document.createElement("span");t.setAttribute("class","autocomplete-infoBox"),t.setAttribute("id","autocomplete-hint"),n.innerHTML=this.hintText,t.appendChild(n),this.infoBox=t,e.parentElement.appendChild(t);}},e.prototype.remove=function(){if(this.infoBox){var e=document.getElementById("autocomplete-hint");e&&e.parentNode&&(e.parentNode.removeChild(e),this.infoBox=void 0);}},e}();

    var AddressAutocomplete=function(){function e(e,t,s,r,i,o){this.navigationKeyCodes=["ArrowUp","ArrowDown","Escape","Enter","Space","Tab"],this.typingDelay=500,this.inputMap=e,this.countrySelect=t,this.deCountryId=s,this.searchService=ServiceFactory.createSearchService(r),this.selectService=ServiceFactory.createSelectService(r),this.addressSuggestions=new AutocompleteAddressSuggestions,this.domAddress=new AutocompleteDomAddress(this.inputMap),this.listRenderer=new ListRenderer,this.hintRenderer=new HintRenderer(i),this.renderSuggestions=o;}return e.prototype.start=function(){var e,t;try{for(var s=__values(this.inputMap.values()),r=s.next();!r.done;r=s.next()){var i=r.value;i.addEventListener("keyup",this.handleFieldKeystroke.bind(this)),i.addEventListener("autocomplete:datalist-select",this.handleDatalistSelect.bind(this));}}catch(t){e={error:t};}finally{try{r&&!r.done&&(t=s.return)&&t.call(s);}finally{if(e)throw e.error}}this.countrySelect.addEventListener("change",this.handleCountryChange.bind(this));},e.prototype.handleFieldKeystroke=function(e){var t=this;this.countrySelect.value===this.deCountryId&&(this.navigationKeyCodes.includes(e.code)||this.triggerDelayedCallback((function(){return t.searchAction(e.target)}),this.typingDelay),"Enter"!==e.code&&this.hintRenderer.remove());},e.prototype.handleDatalistSelect=function(e){var t=e.target,s=t.dataset.suggestionUuid,r=this.addressSuggestions.getByUuid(s),i=this.inputMap.get(AddressInputType$1.Street);r&&(this.domAddress.address=r,this.selectAction(r.uuid),i&&i===t&&this.hintRenderer.render(i));},e.prototype.handleCountryChange=function(){this.countrySelect.value!==this.deCountryId&&this.listRenderer.remove();},e.prototype.triggerDelayedCallback=function(e,t){void 0!==typeof this.timeoutId&&clearTimeout(this.timeoutId),this.timeoutId=window.setTimeout(e,t);},e.prototype.searchAction=function(e){var t=this,s=this.domAddress.address,r=s.street?SearchSubject$1.PostalCodesCitiesStreets:SearchSubject$1.PostalCodesCities;""!==Object.values(s).join("").trim()&&this.searchService.search(this.searchService.requestBuilder.create({country:"de",subject:r,combined:Object.values(s).join(" "),address_type:AddressType$1.A})).then((function(s){t.addressSuggestions.suggestions=s.addresses.filter((function(e){return !!e.uuid})).map((function(e){return {street:e.street||"",postalCode:e.postalCode||"",city:e.city||"",uuid:e.uuid,district:e.district}})),document.dispatchEvent(new CustomEvent("autocomplete:suggestions-retrieve",{detail:{suggestions:t.addressSuggestions.suggestions}})),e===document.activeElement&&t.renderSuggestions&&t.listRenderer.render(e,t.addressSuggestions.suggestions);}));},e.prototype.selectAction=function(e){this.selectService.select(this.selectService.requestBuilder.create({country:"de",subject:SearchSubject$1.PostalCodesCitiesStreets,uuid:e}));},e}();

    var init=function(e,t,d,r,p,s,o,n){void 0===n&&(n=!0);var i=new AddressAutocomplete(new Map([[AddressInputType$1.Street,e],[AddressInputType$1.PostalCode,d],[AddressInputType$1.City,t]]),r,p,s,o,n);return i.start(),i};var postdirektAutocompleteLib = {init:init};

    return postdirektAutocompleteLib;

});
//# sourceMappingURL=postdirekt-autocomplete-lib.amd.js.map
