<?php
/**
 * See LICENSE.md for license details.
 */
/** @var \PostDirekt\Autocomplete\ViewModel\Token $viewModel*/
$viewModel = $block->getViewModel();
$token = $viewModel->getToken();
?>
<script type="text/x-magento-init">
    {
        "*": {
            "PostDirekt_Autocomplete/js/autocomplete-dynamic": {
                "token": "<?= $viewModel->getToken() ?>",
                "fieldNames": {
                    "street": "street[0]",
                    "city": "city",
                    "postalCode": "postcode",
                    "country": "country_id"
                },
                "countryId": "DE"
            }
        }
    }
</script>
