<?php

/**
 * See LICENSE.md for license details.
 */

/** @var \PostDirekt\Autocomplete\ViewModel\Token $viewModel*/
$viewModel = $block->getViewModel();
$token = $viewModel->getToken();
?>
<?php if ($token): ?>
<script type="text/x-magento-init">
    {
        "*": {
            "PostDirekt_Autocomplete/js/autocomplete-static": {
                "token": "<?= $token ?>",
                "fieldNames": {
                    "street": "street[]",
                    "city": "city",
                    "postalCode": "postcode",
                    "country": "country_id"
                },
                "countryId": "DE"
            }
        }
    }
</script>
<?php endif; ?>
