<?php

/**
 * See LICENSE.md for license details.
 */

/**
 * Init component with field names used in Magento_Customer::address/edit.phtml
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \PostDirekt\Autocomplete\ViewModel\Token $viewModel */
$viewModel = $block->getData('view_model');
$token = $viewModel->getToken();
$hint = $viewModel->getHouseNumberHint();
?>
<?php if ($token): ?>
<script type="text/x-magento-init">
    {
        "*": {
            "PostDirekt_Autocomplete/js/autocomplete-static": {
                "token": "<?= $escaper->escapeJs($token) ?>",
                "fieldNames": {
                    "street": "street[0]",
                    "city": "city",
                    "postalCode": "postcode",
                    "country": "country_id"
                },
                "countryId": "DE",
                "hint": "<?= $escaper->escapeHtml($hint) ?>"
            }
        }
    }
</script>
<?php endif; ?>
