<?php
/**
 * See LICENSE.md for license details.
 */
/** @var Magento\Framework\View\Element\Template $block */
?>
<div class="col content">
    <p>
        <?= $block->escapeHtml(__('The DATAFACTORY AUTOCOMPLETE from Deutsche Post Direkt offers effective support for address collection in online business.')) ?>
    </p>
    <p>
        <?= $block->escapeHtml(__('DATAFACTORY AUTOCOMPLETE is easily integrated into your ordering process and conveniently assists during address entry using postal data based on the original Deutsche Post postal routing data.')) ?>
        <?= $block->escapeHtml(__('Address entry during the ordering process is made faster and more convenient, while minimizing address input errors.')) ?>
        <?= $block->escapeHtml(__('Your customer receives up to 15 suggestions as soon as the first alphanumeric characters are entered in the input field.')) ?>
    </p>
    <p>
        <?= $block->escapeHtml(__('More than 1.2 million different address suggestions are available, including all street names relevant for delivery, more than 16,000 postcodes with destinations, 14,000 cities, and 75,000 districts.')) ?>
    </p>

</div>
<div class="col side">
    <aside>
        <div class="section">
            <h2><?= $block->escapeHtml(__('To get started:')) ?></h2>
            <p>
                <?= $block->escapeHtml(__('You need a valid Deutsche Post Direkt account.')) ?>
            </p>
            <p>
                <?= __('If you do not have an account yet or your account is not enabled for DATAFACTORY AUTOCOMPLETE, please use the <a href=\"https://www.postdirekt.de/autocomplete\" target=\"_blank\">Deutsche Post Direkt</a> website to use our address solutions.') ?>
            </p>
        </div>
    </aside>
</div>
